# Generated by Django 4.2.1 on 2023-05-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookacall',
            name='phone_number',
        ),
    ]
